### ISSUE TITLE
Allow re-use of RngRun parameter

### ISSUE THREAD

**Issue by DvdMgr** [DvdMgr/sem#29]
We should devise an ergonomic way to allow users to specify an RngRun parameter together with their simulation parameter combinations. This can come in handy if one wants to compare two simulations using the same RngRun (to get the same placement of buildings and devices, for instance) and compare two different parameter combinations.

**Comment by DvdMgr** [comment]
Implemented in a2f8b68

**Comment by matbord** [comment]
Hi,
where can I find an example of how to re-use the RngRun parameters? I would like to compare two simulations using the same set of RngRun parameters.
I'm actually doing 
```
parameters= #set of parameters for NS3  
runs = 4  
campaign.run_missing_simulations(parameters, runs=runs)
```

Thank you

**Comment by DvdMgr** [comment]
You can omit the `runs` argument in `run_missing_simulations`, and instead specify the desired `RngRun` range directly from the parameter dictionary! So, something along the lines of:

```python
params = {
    'aParameter': [someValue],
    'RngRun': [1, 2, 3]
}
campaign.run_missing_simulations(params)
```
should work. You can also specify `RngRun` in the parameter dictionary you use for queries and to get data out of the database.
